version: "2"
services:
  audio-queue:
    network_mode: host
    restart: always
    build: .
    privileged: true
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
